language: php
php:
  - 5.3
  - 5.4
  
before_script:  
  # Installing pecl_http Module
  - printf "\n\n\n\n" | sudo pecl install pecl_http
  - echo "extension=http.so" | sudo tee $PHP_INI_PATH/http.ini  
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install