language: php
php:
  - 5.3
  - 5.4
  - 5.5
  
before_script:  
  # Installing pecl_http module
  - wget http://pecl.php.net/get/pecl_http-1.7.5.tgz
  - tar -zxf pecl_http-1.7.5.tgz
  - sh -c "cd pecl_http-1.7.5 && phpize && ./configure && make --quiet && sudo make --quiet install"
  - echo "extension=http.so" >> `php --ini | grep "Loaded Configuration" | sed -e "s/.*:\s*//"`
  
  # Install composer for dependency management
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install